-- =====================================================================
-- Idempotent Migration Script: Ensure visitor_activities and other tables exist
-- =====================================================================

-- 1. Ensure __EFMigrationsHistory table exists
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- 2. Synchronize migration history if tables were dropped directly
DO $$
BEGIN
    IF to_regclass('public.visitor_activities') IS NULL THEN
        DELETE FROM "__EFMigrationsHistory" WHERE "MigrationId" LIKE '%CreateVisitorActivitiesTable%';
    END IF;

    IF to_regclass('public.samevistorscount') IS NULL THEN
        DELETE FROM "__EFMigrationsHistory" WHERE "MigrationId" LIKE '%samevistorscount%';
    END IF;
END $$;

-- 3. Initial baseline migration tracking
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260923035808_InitialCreate', '10.0.12')
ON CONFLICT ("MigrationId") DO NOTHING;

-- 4. Create visitor_activities table if it does not exist
CREATE TABLE IF NOT EXISTS visitor_activities (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "VisitorId" bigint NOT NULL,
    "Activity" character varying(200) NOT NULL,
    "Description" character varying(1000),
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "FK_visitor_activities_visitors_VisitorId" FOREIGN KEY ("VisitorId") REFERENCES visitors ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_visitor_activities_VisitorId" ON visitor_activities ("VisitorId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260923040256_CreateVisitorActivitiesTable', '10.0.12')
ON CONFLICT ("MigrationId") DO NOTHING;

-- 5. Create samevistorscount table if it does not exist
CREATE TABLE IF NOT EXISTS samevistorscount (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Phone" character varying(20) NOT NULL,
    "Email" character varying(200) NOT NULL,
    "VisitCount" integer NOT NULL,
    "LastVisitDate" timestamp without time zone NOT NULL
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260923043235_samevistorscount', '10.0.12')
ON CONFLICT ("MigrationId") DO NOTHING;
