using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RoleManagementBackend.Migrations
{
    /// <inheritdoc />
    public partial class CreateVisitorActivitiesTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS visitor_activities (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""VisitorId"" bigint NOT NULL,
                    ""Activity"" character varying(200) NOT NULL,
                    ""Description"" character varying(1000),
                    ""CreatedAt"" timestamp without time zone NOT NULL,
                    CONSTRAINT ""FK_visitor_activities_visitors_VisitorId"" FOREIGN KEY (""VisitorId"") REFERENCES visitors (""Id"") ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ""IX_visitor_activities_VisitorId"" ON visitor_activities (""VisitorId"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS visitor_activities;");
        }
    }
}
