using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RoleManagementBackend.Migrations
{
    /// <inheritdoc />
    public partial class samevistorscount : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS samevistorscount (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Phone"" character varying(20) NOT NULL,
                    ""Email"" character varying(200) NOT NULL,
                    ""VisitCount"" integer NOT NULL,
                    ""LastVisitDate"" timestamp without time zone NOT NULL
                );
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS samevistorscount;");
        }
    }
}